version: '3'

services:
  app:
    build:
      context: .docker.local/app
    ports:
      - 22040:80
    volumes:
      - ./src:/var/www/html
      - ./.docker.local/app/logs/nginx:/var/log/nginx
      - ./.docker.local/app/.composer:/root/.composer
    depends_on:
      - postgres

  postgres:
    build:
      context: .docker.local/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=laravel
    volumes:
      - ./.docker.local/postgres/data:/var/lib/postgresql/data
    ports:
      - 22041:5432